### ISSUE TITLE
HTTP Error 403: Forbidden for Raw Function

### ISSUE THREAD

**Issue by Ironclad17** [radude/rentry#33]
Just trying to upload a text file. The url I requested didn't exist beforehand, but I received a different error than usual. I uploaded the file manually, but the raw function still generates the same error even though it does contain text now.
``` 
Traceback (most recent call last):
  File "C:\Users\*\appdata\roaming\python\python312\site-packages\rentry.py", line 41, in raw
    return json_loads(client.get('https://rentry.co/api/raw/{}'.format(url)).data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\appdata\roaming\python\python312\site-packages\rentry.py", line 25, in get
    return self._request(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\appdata\roaming\python\python312\site-packages\rentry.py", line 33, in _request
    response = self.opener.open(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by Ironclad17** [comment]
Even directly requesting the url still receives the same error. Is it failing on a human verification which I saw on my browser for the same url? Should official api calls have those?
```
>>> import requests
>>> url = '3f40ac76'
>>> requests.get('https://rentry.co/api/raw/{}'.format(url), headers={})
<Response [403]>```

**Comment by Ironclad17** [comment]
I understand changes were made that now require a SECRET_RAW_ACCESS_CODE is now required. I'm reluctant to use this as it requires every user to manually request one via email. I think at this point an api key system is the best option.

**Comment by radude** [comment]
You can also use the access code as a custom header:

rentry-auth = CODE

Which gives access to /raw/ of all pages, making it more like an API key when used like this.

**Comment by Ironclad17** [comment]
I was using it just to check if a url was available or already in use. I guess I can use the edit command instead.

**Comment by radude** [comment]
Most commands should return 'Entry xyz does not exist' if it is not in use. I can look to add a check endpoint returning a bool at some point.
